# Parameter Reduction using Parameter Pruning (کاهش پارامتر با استفاده از کم‌نمونه‌برداری پارامتر)

In [8]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torch.nn.utils.prune as prune

# تعریف مدل
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(784, 256)
        self.fc2 = nn.Linear(256, 128)
        self.fc3 = nn.Linear(128, 10)

    def forward(self, x):
        x = x.view(-1, 784)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

# ایجاد نمونه از مدل
model = Net()

# تعریف تابع هدف (loss function) و بهینه‌ساز
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

# تولید داده‌های آموزش ساده
train_data = torch.randn(1000, 784)
train_labels = torch.randint(0, 10, (1000,))

# تبدیل داده‌ها به TensorDataset
train_dataset = torch.utils.data.TensorDataset(train_data, train_labels)

# تعریف DataLoader برای داده‌های آموزش
trainloader = torch.utils.data.DataLoader(train_dataset, batch_size=64, shuffle=True)

# آموزش مدل با استفاده از داده‌های آموزش
for epoch in range(10):
    running_loss = 0.0
    for i, data in enumerate(trainloader, 0):
        inputs, labels = data
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        running_loss += loss.item()
    print(f"Epoch {epoch+1}: Loss {running_loss/len(trainloader)}")

# کاهش پارامتر با استفاده از کم‌نمونه‌برداری پارامتر
pruned_model = prune.l1_unstructured(model.fc1, name='weight', amount=0.5)

# ارزیابی مدل
test_data = torch.randn(100, 784)
test_labels = torch.randint(0, 10, (100,))
test_dataset = torch.utils.data.TensorDataset(test_data, test_labels)
testloader = torch.utils.data.DataLoader(test_dataset, batch_size=10)

correct = 0
total = 0
with torch.no_grad():
    for data in testloader:
        images, labels = data
        outputs = pruned_model(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()
accuracy = correct / total
print(f"Accuracy: {accuracy}")


Epoch 1: Loss 2.3048331886529922
Epoch 2: Loss 2.3006503134965897
Epoch 3: Loss 2.2961722165346146
Epoch 4: Loss 2.291381984949112
Epoch 5: Loss 2.2872362434864044
Epoch 6: Loss 2.283582255244255
Epoch 7: Loss 2.279708608984947
Epoch 8: Loss 2.275347575545311
Epoch 9: Loss 2.2710374146699905
Epoch 10: Loss 2.2674603015184402
Accuracy: 0.0


# Significant Pruning (کم‌نمونه‌برداری قابل توجه)

In [10]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torch.nn.utils.prune as prune

# تعریف مدل
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(784, 256)
        self.fc2 = nn.Linear(256, 128)
        self.fc3 = nn.Linear(128, 10)

    def forward(self, x):
        x = x.view(-1, 784)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

# ایجاد نمونه از مدل
model = Net()

# تعریف تابع هدف (loss function) و بهینه‌ساز
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

# آموزش مدل با استفاده از داده‌های آموزش
for epoch in range(10):
    running_loss = 0.0
    for i, data in enumerate(trainloader, 0):
        inputs, labels = data
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        running_loss += loss.item()
    print(f"Epoch {epoch+1}: Loss {running_loss/len(trainloader)}")

# کاهش پارامتر با استفاده از کم‌نمونه‌برداری قابل توجه
significant_pruned_model = prune.ln_structured(model.fc1, name='weight', amount=0.5, n=2, dim=0)

# ارزیابی مدل
correct = 0
total = 0
with torch.no_grad():
    for data in testloader:
        images, labels = data
        outputs = significant_pruned_model(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()
accuracy = correct / total
print(f"Accuracy: {accuracy}")

Epoch 1: Loss 2.3065681159496307
Epoch 2: Loss 2.3025631457567215
Epoch 3: Loss 2.298457056283951
Epoch 4: Loss 2.2939128279685974
Epoch 5: Loss 2.289175420999527
Epoch 6: Loss 2.2852788865566254
Epoch 7: Loss 2.2809646874666214
Epoch 8: Loss 2.276397094130516
Epoch 9: Loss 2.272720590233803
Epoch 10: Loss 2.2677572816610336
Accuracy: 0.0


# Weight-based Pruning (کم‌نمونه‌برداری مبتنی بر وزن)

In [11]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torch.nn.utils.prune as prune

# تعریف مدل
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(784, 256)
        self.fc2 = nn.Linear(256, 128)
        self.fc3 = nn.Linear(128, 10)

    def forward(self, x):
        x = x.view(-1, 784)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

# ایجاد نمونه از مدل
model = Net()

# تعریف تابع هدف (loss function) و بهینه‌ساز
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

# آموزش مدل با استفاده از داده‌های آموزش
for epoch in range(10):
    running_loss = 0.0
    for i, data in enumerate(trainloader, 0):
        inputs, labels = data
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        running_loss += loss.item()
    print(f"Epoch {epoch+1}: Loss {running_loss/len(trainloader)}")

# کاهش پارامتر با استفاده از کم‌نمونه‌برداری مبتنی بر وزن
weight_pruned_model = prune.ln_structured(model.fc1, name='weight', amount=0.5, n=2, dim=1)

# ارزیابی مدل
correct = 0
total = 0
with torch.no_grad():
    for data in testloader:
        images, labels = data
        outputs = weight_pruned_model(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()
accuracy = correct / total
print(f"Accuracy: {accuracy}")

Epoch 1: Loss 2.3017091155052185
Epoch 2: Loss 2.297528564929962
Epoch 3: Loss 2.2925126254558563
Epoch 4: Loss 2.288518249988556
Epoch 5: Loss 2.284014046192169
Epoch 6: Loss 2.2798368632793427
Epoch 7: Loss 2.275186687707901
Epoch 8: Loss 2.2710001915693283
Epoch 9: Loss 2.2670977115631104
Epoch 10: Loss 2.2631655037403107
Accuracy: 0.01


#Compare

In [18]:
# تعریف مدل
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(3, 2)
        self.fc2 = nn.Linear(2, 2)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x

# ایجاد نمونه از مدل
model = Net()
print(list(model.named_parameters()))

[('fc1.weight', Parameter containing:
tensor([[ 0.1730,  0.5156,  0.0856],
        [-0.0961, -0.5251, -0.0829]], requires_grad=True)), ('fc1.bias', Parameter containing:
tensor([0.2808, 0.3543], requires_grad=True)), ('fc2.weight', Parameter containing:
tensor([[-0.0294,  0.3842],
        [ 0.0530,  0.6242]], requires_grad=True)), ('fc2.bias', Parameter containing:
tensor([-0.0492,  0.5181], requires_grad=True))]


In [21]:
# ایجاد نمونه از مدل
model = Net()
model=prune.ln_structured(model.fc1, name='weight', amount=0.5, n=2, dim=1)
print(list(model.named_parameters()))

[('bias', Parameter containing:
tensor([0.2213, 0.2622], requires_grad=True)), ('weight_orig', Parameter containing:
tensor([[ 0.3317,  0.4135, -0.2701],
        [-0.0647,  0.2824,  0.4591]], requires_grad=True))]
